# Generated by Django 2.1.2 on 2018-10-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20181003_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewresponse',
            old_name='is_anonymous',
            new_name='anonymous',
        ),
    ]
