# Generated by Django 2.1.2 on 2018-10-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20181003_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewresponse',
            name='anonymous',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
