# Generated by Django 2.1.2 on 2018-10-04 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20181003_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewresponse',
            name='anonymous',
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='response',
            field=models.TextField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='reviewresponse',
            name='review',
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='review',
            field=models.ManyToManyField(blank=True, to='trip.Review'),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL),
        ),
    ]
